"""Initial migration

Revision ID: 435f335adfff
Revises: 
Create Date: 2023-09-12 16:36:19.810881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "435f335adfff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
